In [73]:
import numpy as np
import pandas as pd
df = pd.read_csv('Thesis data.csv')
df.head()

Res_Age  Resp_weight  Resp_height  Anemia_level  Tetanus_BBirth  \
0       38         76.0        1.614             1               3   
1       39         43.8        1.406             3               2   
2       30         65.5        1.597             0               2   
3       32         60.5        1.073             0               3   
4       29         80.1        1.617             0               2   

   HepatitisB_atBirth  ShortBreaths  Married_age  Smoke_at Home  Alcohol  ...  \
0                   0             0           26              0        0  ...   
1                   1             1           24              1        0  ...   
2                   1             0           28              1        0  ...   
3                   0             0           24              1        0  ...   
4                   0             0           24              0        0  ...   

   HeartDisease  Cancer  Kidney  Donatable  DPTB  MMR  Breastfeed_duration  \
0             0       0       0          1     0    0                   24   
1             0       0       0          0     0    0                   12   
2             0       0       0          1     0    0                   13   
3             0       0       0          1     0    0                   39   
4             0       0       0          0     0    0                   24   

   B_ChildSex_Male  ResidenceType_Urban  Transfusion  
0                1                    0          pos  
1                0                    0          neg  
2                1                    0          neg  
3                1                    0          pos  
4                1                    0          pos  

[5 rows x 24 columns]

In [74]:
# حذف مقادیر خالی
df.dropna(inplace=True)
# Check for NaN values:
df.isnull().sum()

Res_Age                0
Resp_weight            0
Resp_height            0
Anemia_level           0
Tetanus_BBirth         0
HepatitisB_atBirth     0
ShortBreaths           0
Married_age            0
Smoke_at Home          0
Alcohol                0
Diabetes               0
Hypertension           0
RespDisease            0
Thyroid                0
HeartDisease           0
Cancer                 0
Kidney                 0
Donatable              0
DPTB                   0
MMR                    0
Breastfeed_duration    0
B_ChildSex_Male        0
ResidenceType_Urban    0
Transfusion            0
dtype: int64

In [75]:
# حذف داده‌های تکراری
df = df.drop_duplicates()

In [76]:
df['Transfusion'].value_counts()

pos    92782
neg    43352
Name: Transfusion, dtype: int64

In [77]:
df.columns

Index(['Res_Age', 'Resp_weight', 'Resp_height', 'Anemia_level',
       'Tetanus_BBirth', 'HepatitisB_atBirth', 'ShortBreaths', 'Married_age',
       'Smoke_at Home', 'Alcohol', 'Diabetes', 'Hypertension', 'RespDisease',
       'Thyroid', 'HeartDisease', 'Cancer', 'Kidney', 'Donatable', 'DPTB',
       'MMR', 'Breastfeed_duration', 'B_ChildSex_Male', 'ResidenceType_Urban',
       'Transfusion'],
      dtype='object')

In [78]:
from sklearn.model_selection import train_test_split

X = df[['Res_Age', 'Resp_weight', 'Resp_height', 'Anemia_level',
       'Tetanus_BBirth', 'HepatitisB_atBirth', 'ShortBreaths', 'Married_age',
       'Smoke_at Home', 'Alcohol', 'Diabetes', 'Hypertension', 'RespDisease',
       'Thyroid', 'HeartDisease', 'Cancer', 'Kidney', 'Donatable', 'DPTB',
       'MMR', 'Breastfeed_duration', 'B_ChildSex_Male', 'ResidenceType_Urban'
       ]]
y = df['Transfusion']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [79]:
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

svc = LinearSVC()
nb = MultinomialNB()
lr = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=11)

# SVC

In [105]:
svc.fit(X_train, y_train)

D:\python2\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [106]:
# Form a prediction set
predictions = svc.predict(X_test)

In [107]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

# Print a classification report
print(metrics.classification_report(y_test,predictions))

[[ 6560  7680]
 [ 1146 29539]]
              precision    recall  f1-score   support

         neg       0.85      0.46      0.60     14240
         pos       0.79      0.96      0.87     30685

   micro avg       0.80      0.80      0.80     44925
   macro avg       0.82      0.71      0.73     44925
weighted avg       0.81      0.80      0.78     44925



In [108]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.8035392320534224


In [109]:
unique, counts = np.unique(predictions, return_counts=True)
dict(zip(unique, counts))

{'neg': 7706, 'pos': 37219}

# naive_bayes

In [135]:
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [136]:
# Form a prediction set
predictions = nb.predict(X_test)

In [137]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

# Print a classification report
print(metrics.classification_report(y_test,predictions))

[[ 7306  6934]
 [ 1343 29342]]
              precision    recall  f1-score   support

         neg       0.84      0.51      0.64     14240
         pos       0.81      0.96      0.88     30685

   micro avg       0.82      0.82      0.82     44925
   macro avg       0.83      0.73      0.76     44925
weighted avg       0.82      0.82      0.80     44925



In [138]:
print(metrics.accuracy_score(y_test,predictions))

0.8157595993322204


In [139]:
unique, counts = np.unique(predictions, return_counts=True)
dict(zip(unique, counts))

{'neg': 8649, 'pos': 36276}

# LogisticRegression

In [140]:
lr.fit(X_train, y_train)

D:\python2\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [141]:
# Form a prediction set
predictions = lr.predict(X_test)

In [142]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

# Print a classification report
print(metrics.classification_report(y_test,predictions))

[[ 7307  6933]
 [ 1349 29336]]
              precision    recall  f1-score   support

         neg       0.84      0.51      0.64     14240
         pos       0.81      0.96      0.88     30685

   micro avg       0.82      0.82      0.82     44925
   macro avg       0.83      0.73      0.76     44925
weighted avg       0.82      0.82      0.80     44925



In [143]:
print(metrics.accuracy_score(y_test,predictions))

0.8156483027267668


In [144]:
unique, counts = np.unique(predictions, return_counts=True)
dict(zip(unique, counts))

{'neg': 8656, 'pos': 36269}

# KNN

In [145]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=11, p=2,
           weights='uniform')

In [146]:
# Form a prediction set
predictions = knn.predict(X_test)

In [147]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

# Print a classification report
print(metrics.classification_report(y_test,predictions))

[[ 3813 10427]
 [ 2349 28336]]
              precision    recall  f1-score   support

         neg       0.62      0.27      0.37     14240
         pos       0.73      0.92      0.82     30685

   micro avg       0.72      0.72      0.72     44925
   macro avg       0.67      0.60      0.59     44925
weighted avg       0.70      0.72      0.68     44925



In [148]:
print(metrics.accuracy_score(y_test,predictions))

0.7156149137451308


In [149]:
unique, counts = np.unique(predictions, return_counts=True)
dict(zip(unique, counts))

{'neg': 6162, 'pos': 38763}